[package]
name = "chess_engine"
version = "1.0.0"
authors = ["Eskil Nyberg <eskilny@kth.se>","Viola Söderlund <violaso@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
